name: Push action
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Fmt
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- -Dwarnings
    - name: Tests
      run: cargo test --verbose
