name: Rust

on: [push, check_suite, check_run]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust Action
      uses: icepuma/rust-action@1.37.0
